package com.schoolmanagement.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class School {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    private String schoolName;
    private String schoolAddress;
    private Long teacherId;

    //Custom constructor without id
    public School(String schoolName, String schoolAddress, Long teacherId) {
        this.schoolName = schoolName;
        this.schoolAddress = schoolAddress;
        this.teacherId = teacherId;
    }
    
    public School() {
    	
    }
    
    // Getters & setters (already generated by Lombok, but you included manually too)
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getSchoolName() {
        return schoolName;
    }
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }
    public String getSchoolAddress() {
        return schoolAddress;
    }
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress;
    }
    public Long getTeacherId() {
        return teacherId;
    }
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }   
}
